FROM nnurphy/js

ENV K8S_VERSION=v1.19.1
ARG kubectl_url=https://dl.k8s.io/${K8S_VERSION}/kubernetes-client-linux-amd64.tar.gz

RUN set -eux \
  ; apt-get update \
  ; DEBIAN_FRONTEND=noninteractive \
        apt-get install -y --no-install-recommends \
        iptables \
  ; curl -s https://packagecloud.io/install/repositories/datawireio/telepresence/script.deb.sh | bash \
  ; apt install -y --no-install-recommends telepresence \
  ; apt-get autoremove -y && apt-get clean -y \
  ; rm -rf /var/lib/apt/lists/* \
  ; wget -q -O- ${kubectl_url} \
    | tar zxf - --strip-components=3 -C /usr/local/bin kubernetes/client/bin/kubectl