FROM amd64/buildpack-deps:focal-scm

ENV just_version=0.7.2
ENV watchexec_version=1.14.0
ENV yq_version=3.3.4
ENV websocat_version=1.6.0
ENV K8S_VERSION=v1.19.1
ARG HELM_VERSION=3.3.1
ARG ISTIO_VERSION=1.7.1

ARG just_url=https://github.com/casey/just/releases/download/v${just_version}/just-v${just_version}-x86_64-unknown-linux-musl.tar.gz
ARG watchexec_url=https://github.com/watchexec/watchexec/releases/download/${watchexec_version}/watchexec-${watchexec_version}-x86_64-unknown-linux-musl.tar.xz
ARG yq_url=https://github.com/mikefarah/yq/releases/download/${yq_version}/yq_linux_amd64
ARG websocat_url=https://github.com/vi/websocat/releases/download/v${websocat_version}/websocat_amd64-linux-static
ARG kubectl_url=https://dl.k8s.io/${K8S_VERSION}/kubernetes-client-linux-amd64.tar.gz

# Install .NET CLI dependencies
RUN set -eux \
  ; apt-get update \
  ; DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        libc6 libgcc1 libgssapi-krb5-2 libicu66 libssl1.1 libstdc++6 zlib1g liblttng-ust0 \
        apt-transport-https gnupg-agent software-properties-common lsb-release \
        zsh git gnupg sudo curl xz-utils net-tools \
  \
  ; curl -fsSL https://download.docker.com/linux/$(lsb_release -is | tr '[:upper:]' '[:lower:]')/gpg | (OUT=$(apt-key add - 2>&1) || echo $OUT) \
  ; add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/$(lsb_release -is | tr '[:upper:]' '[:lower:]') $(lsb_release -cs) stable" \
  ; apt-get update \
  ; apt-get install -y docker-ce-cli \
  \
  ; curl -s https://packagecloud.io/install/repositories/datawireio/telepresence/script.deb.sh | bash \
  ; apt install -y --no-install-recommends telepresence iptables \
  #; update-alternatives --set iptables /usr/sbin/iptables-legacy \
  \
  ; apt-get autoremove -y && apt-get clean -y \
  ; rm -rf /var/lib/apt/lists/* \
  ; wget -q -O- ${just_url} \
    | tar zxf - -C /usr/local/bin just \
  ; wget -q -O- ${watchexec_url} \
    | tar Jxf - --strip-components=1 -C /usr/local/bin watchexec-${watchexec_version}-x86_64-unknown-linux-musl/watchexec \
  ; wget -q -O /usr/local/bin/yq ${yq_url} \
    && chmod +x /usr/local/bin/yq \
  ; wget -q -O /usr/local/bin/websocat ${websocat_url} \
    && chmod +x /usr/local/bin/websocat \
  ; wget -q -O- ${kubectl_url} \
    | tar zxf - --strip-components=3 -C /usr/local/bin kubernetes/client/bin/kubectl \
  ; curl -L https://get.helm.sh/helm-v${HELM_VERSION}-linux-amd64.tar.gz \
        | tar zxvf - -C /usr/local/bin linux-amd64/helm --strip-components=1 \
  ; curl -L https://github.com/istio/istio/releases/download/${ISTIO_VERSION}/istio-${ISTIO_VERSION}-linux-amd64.tar.gz \
        | tar zxvf - -C /usr/local/bin istio-${ISTIO_VERSION}/bin/istioctl --strip-components=2

COPY home /root/

ENV \
    # Enable detection of running in a container
    DOTNET_RUNNING_IN_CONTAINER=true \
    # Enable correct mode for dotnet watch (only mode supported in a container)
    DOTNET_USE_POLLING_FILE_WATCHER=true \
    # Skip extraction of XML docs - generally not useful within an image/container - helps performance
    NUGET_XMLDOC_MODE=skip \
    # PowerShell telemetry for docker image usage
    POWERSHELL_DISTRIBUTION_CHANNEL=PSDocker-DotnetCoreSDK-Ubuntu-20.04

# Install .NET Core SDK
RUN set -eux \
  ; dotnet_sdk_version=2.2.207 \
  ; curl -SL --output dotnet.tar.gz https://dotnetcli.azureedge.net/dotnet/Sdk/$dotnet_sdk_version/dotnet-sdk-$dotnet_sdk_version-linux-x64.tar.gz \
  ; dotnet_sha512='9d70b4a8a63b66da90544087199a0f681d135bf90d43ca53b12ea97cc600a768b0a3d2f824cfe27bd3228e058b060c63319cd86033be8b8d27925283f99de958' \
  ; echo "$dotnet_sha512 dotnet.tar.gz" | sha512sum -c - \
  ; mkdir -p /usr/share/dotnet \
  ; tar -ozxf dotnet.tar.gz -C /usr/share/dotnet \
  ; rm dotnet.tar.gz \
  ; ln -s /usr/share/dotnet/dotnet /usr/bin/dotnet \
  # Trigger first run experience by running arbitrary cmd
  ; dotnet help



