FROM nnurphy/phpf:7.2

ENV K8S_VERSION=v1.19.1
ARG kubectl_url=https://dl.k8s.io/${K8S_VERSION}/kubernetes-client-linux-amd64.tar.gz
ARG HELM_VERSION=3.3.1
ARG ISTIO_VERSION=1.7.1

RUN set -eux \
  ; apt-get update \
  ; DEBIAN_FRONTEND=noninteractive \
        apt-get install -y --no-install-recommends \
        apt-transport-https gnupg-agent software-properties-common lsb-release \
  ; curl -fsSL https://download.docker.com/linux/$(lsb_release -is | tr '[:upper:]' '[:lower:]')/gpg | (OUT=$(apt-key add - 2>&1) || echo $OUT) \
  ; add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/$(lsb_release -is | tr '[:upper:]' '[:lower:]') $(lsb_release -cs) stable" \
  ; apt-get update \
  ; apt-get install -y docker-ce-cli \
  \
  ; curl -s https://packagecloud.io/install/repositories/datawireio/telepresence/script.deb.sh | bash \
  ; apt install -y --no-install-recommends telepresence iptables \
  ; update-alternatives --set iptables /usr/sbin/iptables-legacy \
  \
  ; apt-get autoremove -y && apt-get clean -y \
  ; rm -rf /var/lib/apt/lists/* \
  ; wget -q -O- ${kubectl_url} \
    | tar zxf - --strip-components=3 -C /usr/local/bin kubernetes/client/bin/kubectl \
  ; curl -L https://get.helm.sh/helm-v${HELM_VERSION}-linux-amd64.tar.gz \
        | tar zxvf - -C /usr/local/bin linux-amd64/helm --strip-components=1 \
  ; curl -L https://github.com/istio/istio/releases/download/${ISTIO_VERSION}/istio-${ISTIO_VERSION}-linux-amd64.tar.gz \
        | tar zxvf - -C /usr/local/bin istio-${ISTIO_VERSION}/bin/istioctl --strip-components=2
